name: Build docs

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install mkdocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      - name: Build site
        run: mkdocs build --clean
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/
